#!/bin/bash

echo "=================================="
echo "🎉 ADMIN LOGIN IS NOW READY!"
echo "=================================="
echo ""
echo "✅ Server is running on port 8000"
echo ""
echo "📝 LOGIN INSTRUCTIONS:"
echo "=================================="
echo ""
echo "1️⃣  Open your web browser (Chrome, Firefox, etc.)"
echo ""
echo "2️⃣  Go to this URL:"
echo "    👉 http://localhost:8000/admin/login"
echo ""
echo "3️⃣  Login with these credentials:"
echo "    Username: admin"
echo "    Password: admin123"
echo ""
echo "4️⃣  After login, you'll be redirected to the admin dashboard"
echo ""
echo "5️⃣  Click 'Usage' in the navigation to see your dashboard!"
echo ""
echo "=================================="
echo "📊 WHAT YOU'LL SEE:"
echo "=================================="
echo "   • Summary cards with key metrics"
echo "   • Interactive charts (Chart.js)"
echo "   • Top users and projects"
echo "   • Quota status with color warnings"
echo "   • Recent operations log"
echo "   • Time range filter (24h/7d/30d/all)"
echo ""
echo "=================================="
echo "🔗 QUICK LINKS:"
echo "=================================="
echo "   Login:     http://localhost:8000/admin/login"
echo "   Dashboard: http://localhost:8000/admin"
echo "   Usage:     http://localhost:8000/admin/usage"
echo ""
echo "=================================="
echo ""

# Test if server is responding
if curl -s "http://localhost:8000/admin/login" > /dev/null 2>&1; then
    echo "✅ Server is responding!"
    echo ""
    echo "🚀 Ready to go! Open your browser now!"
else
    echo "❌ Server is not responding on port 8000"
    echo "   Try running: python3 main.py"
fi

echo ""
