# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embeddings.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'embeddings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65mbeddings.proto\x12\nembeddings\"B\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x11\n\tnormalize\x18\x03 \x01(\x08\"A\n\rEmbedResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\x12\x11\n\tembedding\x18\x03 \x03(\x02\"H\n\x11\x45mbedBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x11\n\tnormalize\x18\x03 \x01(\x08\"]\n\x12\x45mbedBatchResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\x12(\n\x05items\x18\x03 \x03(\x0b\x32\x19.embeddings.EmbeddingItem\"1\n\rEmbeddingItem\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x11\n\tembedding\x18\x02 \x03(\x02\"\x0f\n\rHealthRequest\"O\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\x12\x0b\n\x03\x64im\x18\x04 \x01(\x05\x32\xdf\x01\n\x11\x45mbeddingsService\x12<\n\x05\x45mbed\x12\x18.embeddings.EmbedRequest\x1a\x19.embeddings.EmbedResponse\x12K\n\nEmbedBatch\x12\x1d.embeddings.EmbedBatchRequest\x1a\x1e.embeddings.EmbedBatchResponse\x12?\n\x06Health\x12\x19.embeddings.HealthRequest\x1a\x1a.embeddings.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embeddings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDREQUEST']._serialized_start=32
  _globals['_EMBEDREQUEST']._serialized_end=98
  _globals['_EMBEDRESPONSE']._serialized_start=100
  _globals['_EMBEDRESPONSE']._serialized_end=165
  _globals['_EMBEDBATCHREQUEST']._serialized_start=167
  _globals['_EMBEDBATCHREQUEST']._serialized_end=239
  _globals['_EMBEDBATCHRESPONSE']._serialized_start=241
  _globals['_EMBEDBATCHRESPONSE']._serialized_end=334
  _globals['_EMBEDDINGITEM']._serialized_start=336
  _globals['_EMBEDDINGITEM']._serialized_end=385
  _globals['_HEALTHREQUEST']._serialized_start=387
  _globals['_HEALTHREQUEST']._serialized_end=402
  _globals['_HEALTHRESPONSE']._serialized_start=404
  _globals['_HEALTHRESPONSE']._serialized_end=483
  _globals['_EMBEDDINGSSERVICE']._serialized_start=486
  _globals['_EMBEDDINGSSERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
