# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import embeddings_pb2 as proto_dot_embeddings__pb2


class EmbeddingsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/embeddings.EmbeddingsService/Embed',
                request_serializer=proto_dot_embeddings__pb2.EmbedRequest.SerializeToString,
                response_deserializer=proto_dot_embeddings__pb2.EmbedResponse.FromString,
                )
        self.EmbedBatch = channel.unary_unary(
                '/embeddings.EmbeddingsService/EmbedBatch',
                request_serializer=proto_dot_embeddings__pb2.EmbedBatchRequest.SerializeToString,
                response_deserializer=proto_dot_embeddings__pb2.EmbedBatchResponse.FromString,
                )
        self.Health = channel.unary_unary(
                '/embeddings.EmbeddingsService/Health',
                request_serializer=proto_dot_embeddings__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_embeddings__pb2.HealthResponse.FromString,
                )


class EmbeddingsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=proto_dot_embeddings__pb2.EmbedRequest.FromString,
                    response_serializer=proto_dot_embeddings__pb2.EmbedResponse.SerializeToString,
            ),
            'EmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedBatch,
                    request_deserializer=proto_dot_embeddings__pb2.EmbedBatchRequest.FromString,
                    response_serializer=proto_dot_embeddings__pb2.EmbedBatchResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=proto_dot_embeddings__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_embeddings__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embeddings.EmbeddingsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbeddingsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embeddings.EmbeddingsService/Embed',
            proto_dot_embeddings__pb2.EmbedRequest.SerializeToString,
            proto_dot_embeddings__pb2.EmbedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embeddings.EmbeddingsService/EmbedBatch',
            proto_dot_embeddings__pb2.EmbedBatchRequest.SerializeToString,
            proto_dot_embeddings__pb2.EmbedBatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embeddings.EmbeddingsService/Health',
            proto_dot_embeddings__pb2.HealthRequest.SerializeToString,
            proto_dot_embeddings__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
