# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/embeddings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/embeddings.proto\x12\nembeddings\"B\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x11\n\tnormalize\x18\x03 \x01(\x08\"A\n\rEmbedResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\x12\x11\n\tembedding\x18\x03 \x03(\x02\"H\n\x11\x45mbedBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x11\n\tnormalize\x18\x03 \x01(\x08\"]\n\x12\x45mbedBatchResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\x12(\n\x05items\x18\x03 \x03(\x0b\x32\x19.embeddings.EmbeddingItem\"1\n\rEmbeddingItem\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x11\n\tembedding\x18\x02 \x03(\x02\"\x0f\n\rHealthRequest\"O\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\x12\x0b\n\x03\x64im\x18\x04 \x01(\x05\x32\xdf\x01\n\x11\x45mbeddingsService\x12<\n\x05\x45mbed\x12\x18.embeddings.EmbedRequest\x1a\x19.embeddings.EmbedResponse\x12K\n\nEmbedBatch\x12\x1d.embeddings.EmbedBatchRequest\x1a\x1e.embeddings.EmbedBatchResponse\x12?\n\x06Health\x12\x19.embeddings.HealthRequest\x1a\x1a.embeddings.HealthResponseb\x06proto3')



_EMBEDREQUEST = DESCRIPTOR.message_types_by_name['EmbedRequest']
_EMBEDRESPONSE = DESCRIPTOR.message_types_by_name['EmbedResponse']
_EMBEDBATCHREQUEST = DESCRIPTOR.message_types_by_name['EmbedBatchRequest']
_EMBEDBATCHRESPONSE = DESCRIPTOR.message_types_by_name['EmbedBatchResponse']
_EMBEDDINGITEM = DESCRIPTOR.message_types_by_name['EmbeddingItem']
_HEALTHREQUEST = DESCRIPTOR.message_types_by_name['HealthRequest']
_HEALTHRESPONSE = DESCRIPTOR.message_types_by_name['HealthResponse']
EmbedRequest = _reflection.GeneratedProtocolMessageType('EmbedRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDREQUEST,
  '__module__' : 'proto.embeddings_pb2'
  # @@protoc_insertion_point(class_scope:embeddings.EmbedRequest)
  })
_sym_db.RegisterMessage(EmbedRequest)

EmbedResponse = _reflection.GeneratedProtocolMessageType('EmbedResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDRESPONSE,
  '__module__' : 'proto.embeddings_pb2'
  # @@protoc_insertion_point(class_scope:embeddings.EmbedResponse)
  })
_sym_db.RegisterMessage(EmbedResponse)

EmbedBatchRequest = _reflection.GeneratedProtocolMessageType('EmbedBatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDBATCHREQUEST,
  '__module__' : 'proto.embeddings_pb2'
  # @@protoc_insertion_point(class_scope:embeddings.EmbedBatchRequest)
  })
_sym_db.RegisterMessage(EmbedBatchRequest)

EmbedBatchResponse = _reflection.GeneratedProtocolMessageType('EmbedBatchResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDBATCHRESPONSE,
  '__module__' : 'proto.embeddings_pb2'
  # @@protoc_insertion_point(class_scope:embeddings.EmbedBatchResponse)
  })
_sym_db.RegisterMessage(EmbedBatchResponse)

EmbeddingItem = _reflection.GeneratedProtocolMessageType('EmbeddingItem', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGITEM,
  '__module__' : 'proto.embeddings_pb2'
  # @@protoc_insertion_point(class_scope:embeddings.EmbeddingItem)
  })
_sym_db.RegisterMessage(EmbeddingItem)

HealthRequest = _reflection.GeneratedProtocolMessageType('HealthRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHREQUEST,
  '__module__' : 'proto.embeddings_pb2'
  # @@protoc_insertion_point(class_scope:embeddings.HealthRequest)
  })
_sym_db.RegisterMessage(HealthRequest)

HealthResponse = _reflection.GeneratedProtocolMessageType('HealthResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHRESPONSE,
  '__module__' : 'proto.embeddings_pb2'
  # @@protoc_insertion_point(class_scope:embeddings.HealthResponse)
  })
_sym_db.RegisterMessage(HealthResponse)

_EMBEDDINGSSERVICE = DESCRIPTOR.services_by_name['EmbeddingsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMBEDREQUEST._serialized_start=38
  _EMBEDREQUEST._serialized_end=104
  _EMBEDRESPONSE._serialized_start=106
  _EMBEDRESPONSE._serialized_end=171
  _EMBEDBATCHREQUEST._serialized_start=173
  _EMBEDBATCHREQUEST._serialized_end=245
  _EMBEDBATCHRESPONSE._serialized_start=247
  _EMBEDBATCHRESPONSE._serialized_end=340
  _EMBEDDINGITEM._serialized_start=342
  _EMBEDDINGITEM._serialized_end=391
  _HEALTHREQUEST._serialized_start=393
  _HEALTHREQUEST._serialized_end=408
  _HEALTHRESPONSE._serialized_start=410
  _HEALTHRESPONSE._serialized_end=489
  _EMBEDDINGSSERVICE._serialized_start=492
  _EMBEDDINGSSERVICE._serialized_end=715
# @@protoc_insertion_point(module_scope)
