from typing import List, Protocol


class EncoderPort(Protocol):
    def dim(self) -> int: ...
    def encode(
        self, texts: List[str], task_type: str = "passage", normalize: bool = True
    ) -> List[List[float]]: ...
    def device(self) -> str: ...
    def model_id(self) -> str: ...
    def batch_size(self) -> int: ...
